<a href="https://colab.research.google.com/github/GAYATHRI-2002/100DaysOfCode/blob/master/dataTransformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('mpg')

In [3]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [5]:
df['horsepower'].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
        nan, 100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,
        65.,  69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137.,
       158., 167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,
        78.,  52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,
        81.,  79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,
        48.,  66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62.,
       132.,  84.,  64.,  74., 116.,  82.])

In [6]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [8]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [10]:
df['horsepower'] = df['horsepower'].astype('int')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [12]:
df['power_to_weight'] = df['horsepower']/df['weight']
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,power_to_weight
0,18.0,8,307.0,130,3504,12.0,70,usa,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165,3693,11.5,70,usa,buick skylark 320,0.044679
2,18.0,8,318.0,150,3436,11.0,70,usa,plymouth satellite,0.043655
3,16.0,8,304.0,150,3433,12.0,70,usa,amc rebel sst,0.043694
4,17.0,8,302.0,140,3449,10.5,70,usa,ford torino,0.040591

In [13]:
df['origin'].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [14]:
origin_map = {'usa':'USA','europe':'Europe','japan':'Japan'}
df['origin'] = df['origin'].map(origin_map)

In [15]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,power_to_weight
0,18.0,8,307.0,130,3504,12.0,70,USA,chevrolet chevelle malibu,0.037100
1,15.0,8,350.0,165,3693,11.5,70,USA,buick skylark 320,0.044679
2,18.0,8,318.0,150,3436,11.0,70,USA,plymouth satellite,0.043655
3,16.0,8,304.0,150,3433,12.0,70,USA,amc rebel sst,0.043694
4,17.0,8,302.0,140,3449,10.5,70,USA,ford torino,0.040591

In [16]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,power_to_weight
393,27.0,4,140.0,86,2790,15.6,82,USA,ford mustang gl,0.030824
394,44.0,4,97.0,52,2130,24.6,82,Europe,vw pickup,0.024413
395,32.0,4,135.0,84,2295,11.6,82,USA,dodge rampage,0.036601
396,28.0,4,120.0,79,2625,18.6,82,USA,ford ranger,0.030095
397,31.0,4,119.0,82,2720,19.4,82,USA,chevy s-10,0.030147

In [17]:
highmpg = df[df['mpg'] > 30]

In [18]:
highmpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,power_to_weight
53,31.0,4,71.0,65,1773,19.0,71,Japan,toyota corolla 1200,0.036661
54,35.0,4,72.0,69,1613,18.0,71,Japan,datsun 1200,0.042777
129,31.0,4,79.0,67,1950,19.0,74,Japan,datsun b210,0.034359
131,32.0,4,71.0,65,1836,21.0,74,Japan,toyota corolla 1200,0.035403
144,31.0,4,76.0,52,1649,16.5,74,Japan,toyota corona,0.031534

In [20]:
highmpg.shape

(85, 10)

In [22]:
japan_hp = df[(df['origin']=='Japan') & (df['horsepower']>100)]

In [23]:
japan_hp.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,power_to_weight
123,20.0,6,156.0,122,2807,13.5,73,Japan,toyota mark ii,0.043463
210,19.0,6,156.0,108,2930,15.5,76,Japan,toyota mark ii,0.036860
243,21.5,3,80.0,110,2720,13.5,77,Japan,mazda rx-4,0.040441
333,32.7,6,168.0,132,2910,11.4,80,Japan,datsun 280-zx,0.045361
361,25.4,6,168.0,116,2900,12.6,81,Japan,toyota cressida,0.040000

In [24]:
japan_hp.shape

(6, 10)

In [25]:
light_effi = df[(df['weight'] < 2500) & (df['mpg'] > 25)]
light_effi.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,power_to_weight
18,27.0,4,97.0,88,2130,14.5,70,Japan,datsun pl510,0.041315
19,26.0,4,97.0,46,1835,20.5,70,Europe,volkswagen 1131 deluxe sedan,0.025068
23,26.0,4,121.0,113,2234,12.5,70,Europe,bmw 2002,0.050582
29,27.0,4,97.0,88,2130,14.5,71,Japan,datsun pl510,0.041315
30,28.0,4,140.0,90,2264,15.5,71,USA,chevrolet vega 2300,0.039753

In [26]:
light_effi.shape

(118, 10)

In [27]:
df['mpg']

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [28]:
df_subset = df[['mpg', 'horsepower', 'weight']]

In [29]:
df_subset

      mpg  horsepower  weight
0    18.0         130    3504
1    15.0         165    3693
2    18.0         150    3436
3    16.0         150    3433
4    17.0         140    3449
..    ...         ...     ...
393  27.0          86    2790
394  44.0          52    2130
395  32.0          84    2295
396  28.0          79    2625
397  31.0          82    2720

[398 rows x 3 columns]

In [31]:
auto = sns.load_dataset('mpg')

In [32]:
grouped = auto.groupby('origin')